### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by carloliveros** [uym2/TreeShrink#4]
I encountered a run time error running treeshrink  with 4307 gene trees and 396 taxa.  It has worked with no issues with 4060 gene trees and 221 taxa.  Here's the screen output:

... a bunch of lines
Solving k-shrink with k = 94
Solving k-shrink with k = 96
Traceback (most recent call last):
  File "/home/oliveros/TreeShrink/run_treeshrink.py", line 243, in <module>
    main()
  File "/home/oliveros/TreeShrink/run_treeshrink.py", line 197, in main
    trees_shrunk = deepcopy(trees)
  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/oliveros/TreeShrink/dendropy/datamodel/treecollectionmodel.py", line 483, in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
  File "/home/oliveros/TreeShrink/dendropy/datamodel/basemodel.py", line 784, in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/oliveros/TreeShrink/dendropy/datamodel/treemodel.py", line 3243, in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
  File "/home/oliveros/TreeShrink/dendropy/datamodel/basemodel.py", line 784, in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
... a bunch of lines

  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/home/oliveros/TreeShrink/dendropy/datamodel/treemodel.py", line 1017, in __deepcopy__
    return basemodel.Annotable.__deepcopy__(self, memo=memo)
  File "/home/oliveros/TreeShrink/dendropy/datamodel/basemodel.py", line 784, in __deepcopy__
    other.__dict__[k] = copy.deepcopy(self.__dict__[k], memo)
  File "/home/oliveros/anaconda/lib/python2.7/copy.py", line 155, in deepcopy
    y = memo.get(d, _nil)
RuntimeError: maximum recursion depth exceeded in cmp

Any suggested fix?

-Carl

**Comment by smirarab** [comment]
Can you try adding:

~~~
sys.setrecursionlimit(5000)
~~~

to the first line of `TreeShrink/run_treeshrink.py`

and see if that fixes your problem? If it does, I will make that a bugfix.

**Comment by smirarab** [comment]
Uyen, should we set this as default? Perhaps we already do?
