### ISSUE TITLE
No module named treeshrink.sequence_lib

### ISSUE THREAD

**Issue by BioinfoAK** [uym2/TreeShrink#43]
Hi all, 

I am trying to use TreeShrink on my HPC account. 

I have downloaded TreeShrink via conda and via Git. When I try to check that everything is okay by running run_treeshrink -h, I get the same issue in both cases: 
```

Traceback (most recent call last):
  File "/home/ak5g21/.conda/envs/dnds/bin/run_treeshrink", line 3, in <module>
    from treeshrink.sequence_lib import sample_from_list
ImportError: No module named treeshrink.sequence_lib
```

I do not understand what treeshrink.sequence_lib and how to download it/fix the issue. Does anyone have any suggestions? 

Many thanks!

**Comment by rj-moore** [comment]
Hello, 

I'm also having a similar problem and haven't been able to find a way to fix this yet:

```
Traceback (most recent call last):
  File "/mnt/shared/scratch/username/apps/conda/envs/python3.8/bin/run_treeshrink.py", line 3, in <module>
    from treeshrink.sequence_lib import sample_from_list
ModuleNotFoundError: No module named 'treeshrink'
```

Any help would be greatly appreciated!
