### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by bruceamurphy** [uym2/TreeShrink#5]
Installing as suggested in the documentation leads to moduleNotFoundError unless TreeShrink/treeshrink directory is added to the PYTHONPATH:

`Traceback (most recent call last):
  File "/rds/general/user/******/home/software/TreeShrink/run_treeshrink.py", line 243, in <module>
    main()
  File "/rds/general/user/******/home/software/TreeShrink/run_treeshrink.py", line 6, in main
    from treeshrink.optimal_filter_lib import TreeFilter
  File "/rds/general/user/******/home/software/TreeShrink/treeshrink/optimal_filter_lib.py", line 10, in <module>
    from Tree_extend import Centroid_Tree, MPR_Tree
ModuleNotFoundError: No module named 'Tree_extend'
`

Should the relevant code in optimal_filter_lib.py perhaps be:

`
from treeshrink.Tree_extend import Centroid_Tree, MPR_Tree
`

rather than:

`
from Tree_extend import Centroid_Tree, MPR_Tree
`

**Comment by smirarab** [comment]
Sorry, the updates seem to have been pushed prematurely. Can you check the current version? Note the changes in the README file, including the updated installation guide.
